/* Assessoria Habitatge — Main JS */
const T={ca:{nav_home:'Inici',nav_project:'El Projecte',nav_assessoria:'Assessoria',nav_propcheck:'Valoració',nav_blog:'Blog',nav_docs:'Documentació',nav_press:'Premsa',nav_contact:'Contacte',hero_badge:'Eina gratuïta per a Catalunya',hero_t1:'La teva guia per a',hero_t2:"l'habitatge a Catalunya",hero_desc:'Analitza preus, calcula hipoteques, compara municipis i rep orientació personalitzada. Tot gratuït, amb dades reals.',hero_btn1:'Assessoria completa',hero_btn2:'Valorar immoble',stat1:'Municipis',stat2:'Gratuït',stat3:'En 2 minuts',fo:'Què oferim',ft:'Eines per prendre millors decisions',fd:"Tot el que necessites per entendre el mercat immobiliari i prendre decisions amb confiança.",f1t:'Assessoria financera',f1d:"Calcula la teva hipoteca, analitza el teu perfil financer i rep un pla d'acció personalitzat amb IA.",f2t:"Valoració d'immobles",f2d:"Descobreix si el preu que et demanen és just. Compara amb dades reals del mercat català.",f3t:'Comparador de municipis',f3d:"Compara preus, serveis i qualitat de vida entre municipis del Baix Penedès i tota Catalunya.",f4t:'Blog actualitzat',f4d:"Articles, guies i anàlisis sobre el mercat immobiliari, ajuts i consells per a joves.",f5t:'Documentació gratuïta',f5d:'Checklists de visita, guies per a propietaris, tests personalitzats i més — tot descarregable.',f6t:'Dades oficials',f6d:"Basem les nostres recomanacions en dades de l'Idescat, Generalitat i registres oficials.",to:'Testimonis',tt:'Què en diuen els nostres usuaris',bo:'Blog Actualitat',bt:'Últims articles',bbtn:'Veure tots els articles',bread:'Llegeix-ne més →',cta_t:'Comença a analitzar el teu habitatge',cta_d:"Eines gratuïtes, dades reals i orientació professional. Sense compromís.",cta_b:'Començar ara',fdesc:"Plataforma d'assessoria d'habitatge gratuïta per a Catalunya.",ftools:'Eines',fres:'Recursos',fleg:'Legal',fpriv:'Política de privacitat',fcook:'Política de cookies',fterm:'Avís legal',frights:'© 2026 Assessoria Habitatge. Tots els drets reservats.',fdisc:'Eina orientativa. Els preus són estimats. No substitueix assessorament professional.',ckt:'Utilitzem cookies per millorar la teva experiència.',cka:'Acceptar',ckr:'Rebutjar',ckp:'Política de cookies',cnt:'Contacte',cnd:"Tens dubtes? Escriu-nos i t'atendrem.",cnn:'Nom complet',cne:'Correu electrònic',cnm:'Missatge',cns:'Enviar missatge',cnl:'Ubicació',cnh:'Horari',cnhv:'Dl-Dv, 9:00-18:00',pt:'El Projecte',pd:"Coneix la història i la missió d'Assessoria d'Habitatge.",at:'Assessoria Completa',ad:"Calcula hipoteques, analitza el teu perfil financer i rep un pla d'acció personalitzat.",vt:"Valoració d'Immobles",vd:"Comprova si el preu d'un immoble és just.",bpt:'Blog Actualitat',bpd:"Articles i anàlisis sobre l'habitatge a Catalunya.",dt:'Documentació i recursos',dd:'Materials gratuïts descarregables.',prt:'Premsa i mencions',prd:"Mitjans que han parlat d'Assessoria d'Habitatge."},
es:{nav_home:'Inicio',nav_project:'El Proyecto',nav_assessoria:'Asesoría',nav_propcheck:'Valoración',nav_blog:'Blog',nav_docs:'Documentación',nav_press:'Prensa',nav_contact:'Contacto',hero_badge:'Herramienta gratuita para Cataluña',hero_t1:'Tu guía para la',hero_t2:'vivienda en Cataluña',hero_desc:'Analiza precios, calcula hipotecas, compara municipios y recibe orientación personalizada. Todo gratis, con datos reales.',hero_btn1:'Asesoría completa',hero_btn2:'Valorar inmueble',stat1:'Municipios',stat2:'Gratuito',stat3:'En 2 minutos',fo:'Qué ofrecemos',ft:'Herramientas para tomar mejores decisiones',fd:'Todo lo que necesitas para entender el mercado inmobiliario y decidir con confianza.',f1t:'Asesoría financiera',f1d:'Calcula tu hipoteca, analiza tu perfil financiero y recibe un plan de acción personalizado con IA.',f2t:'Valoración de inmuebles',f2d:'Descubre si el precio que te piden es justo. Compara con datos reales del mercado catalán.',f3t:'Comparador de municipios',f3d:'Compara precios, servicios y calidad de vida entre municipios del Baix Penedès y toda Cataluña.',f4t:'Blog actualizado',f4d:'Artículos, guías y análisis sobre el mercado inmobiliario, ayudas y consejos para jóvenes.',f5t:'Documentación gratuita',f5d:'Checklists de visita, guías para propietarios, tests personalizados y más — todo descargable.',f6t:'Datos oficiales',f6d:'Basamos nuestras recomendaciones en datos del Idescat, Generalitat y registros oficiales.',to:'Testimonios',tt:'Lo que dicen nuestros usuarios',bo:'Blog Actualidad',bt:'Últimos artículos',bbtn:'Ver todos los artículos',bread:'Leer más →',cta_t:'Empieza a analizar tu vivienda',cta_d:'Herramientas gratuitas, datos reales y orientación profesional. Sin compromiso.',cta_b:'Empezar ahora',fdesc:'Plataforma de asesoría de vivienda gratuita para Cataluña.',ftools:'Herramientas',fres:'Recursos',fleg:'Legal',fpriv:'Política de privacidad',fcook:'Política de cookies',fterm:'Aviso legal',frights:'© 2026 Assessoria Habitatge. Todos los derechos reservados.',fdisc:'Herramienta orientativa. Los precios son estimados. No sustituye asesoramiento profesional.',ckt:'Usamos cookies para mejorar tu experiencia.',cka:'Aceptar',ckr:'Rechazar',ckp:'Política de cookies',cnt:'Contacto',cnd:'¿Tienes dudas? Escríbenos y te atenderemos.',cnn:'Nombre completo',cne:'Correo electrónico',cnm:'Mensaje',cns:'Enviar mensaje',cnl:'Ubicación',cnh:'Horario',cnhv:'Lun-Vie, 9:00-18:00',pt:'El Proyecto',pd:'Conoce la historia y misión de Assessoria d\'Habitatge.',at:'Asesoría Completa',ad:'Calcula hipotecas, analiza tu perfil financiero y recibe un plan personalizado.',vt:'Valoración de Inmuebles',vd:'Comprueba si el precio de un inmueble es justo.',bpt:'Blog Actualidad',bpd:'Artículos y análisis sobre la vivienda en Cataluña.',dt:'Documentación y recursos',dd:'Materiales gratuitos descargables.',prt:'Prensa y menciones',prd:'Medios que han hablado de Assessoria d\'Habitatge.'},
en:{nav_home:'Home',nav_project:'The Project',nav_assessoria:'Advisory',nav_propcheck:'Valuation',nav_blog:'Blog',nav_docs:'Docs',nav_press:'Press',nav_contact:'Contact',hero_badge:'Free tool for Catalonia',hero_t1:'Your guide to',hero_t2:'housing in Catalonia',hero_desc:'Analyze prices, calculate mortgages, compare municipalities and get personalized guidance. All free, with real data.',hero_btn1:'Full advisory',hero_btn2:'Property valuation',stat1:'Municipalities',stat2:'Free',stat3:'In 2 minutes',fo:'What we offer',ft:'Tools for better decisions',fd:'Everything you need to understand the real estate market and decide with confidence.',f1t:'Financial advisory',f1d:'Calculate your mortgage, analyze your financial profile and get a personalized action plan with AI.',f2t:'Property valuation',f2d:'Find out if the asking price is fair. Compare with real Catalan market data.',f3t:'Municipality comparator',f3d:'Compare prices, services and quality of life between municipalities across Catalonia.',f4t:'Updated blog',f4d:'Articles, guides and analysis on the real estate market, aid and advice for young people.',f5t:'Free documentation',f5d:'Visit checklists, owner guides, personalized tests and more — all downloadable.',f6t:'Official data',f6d:'We base our recommendations on data from Idescat, Generalitat and official registries.',to:'Testimonials',tt:'What our users say',bo:'Blog',bt:'Latest articles',bbtn:'View all articles',bread:'Read more →',cta_t:'Start analyzing your housing',cta_d:'Free tools, real data and professional guidance. No commitment.',cta_b:'Start now',fdesc:'Free housing advisory platform for Catalonia.',ftools:'Tools',fres:'Resources',fleg:'Legal',fpriv:'Privacy policy',fcook:'Cookie policy',fterm:'Legal notice',frights:'© 2026 Assessoria Habitatge. All rights reserved.',fdisc:'Indicative tool. Prices are estimated. Does not replace professional advice.',ckt:'We use cookies to improve your experience.',cka:'Accept',ckr:'Reject',ckp:'Cookie policy',cnt:'Contact',cnd:'Have questions? Write to us.',cnn:'Full name',cne:'Email',cnm:'Message',cns:'Send message',cnl:'Location',cnh:'Hours',cnhv:'Mon-Fri, 9:00-18:00',pt:'The Project',pd:'Learn about the history and mission of Assessoria d\'Habitatge.',at:'Full Advisory',ad:'Calculate mortgages, analyze your financial profile and get a personalized plan.',vt:'Property Valuation',vd:'Check if a property price is fair.',bpt:'Blog',bpd:'Articles and analysis about housing in Catalonia.',dt:'Documentation & Resources',dd:'Free downloadable materials.',prt:'Press & Mentions',prd:'Media that have featured Assessoria d\'Habitatge.'}};

let LANG=localStorage.getItem('ah_lang')||'ca';

function setLang(l){
  LANG=l;localStorage.setItem('ah_lang',l);document.documentElement.lang=l;
  document.querySelectorAll('[data-t]').forEach(el=>{
    const k=el.dataset.t,v=T[l]?.[k];
    if(v){if(el.tagName==='INPUT'||el.tagName==='TEXTAREA')el.placeholder=v;else el.textContent=v;}
  });
  document.querySelectorAll('.lang button').forEach(b=>b.classList.toggle('active',b.dataset.l===l));
}

document.addEventListener('DOMContentLoaded',()=>{
  // Nav
  const nav=document.querySelector('.nav'),tog=document.querySelector('.burger'),links=document.querySelector('.nav-links');
  if(nav)window.addEventListener('scroll',()=>nav.style.boxShadow=window.scrollY>10?'0 2px 12px rgba(0,0,0,.06)':'none',{passive:true});
  if(tog&&links){tog.onclick=()=>{links.classList.toggle('open');tog.setAttribute('aria-expanded',links.classList.contains('open'))};links.querySelectorAll('a').forEach(a=>a.onclick=()=>links.classList.remove('open'))}
  document.querySelectorAll('.lang button').forEach(b=>b.onclick=()=>setLang(b.dataset.l));
  
  // Active link
  const p=location.pathname.split('/').pop()||'index.html';
  document.querySelectorAll('.nav-links a').forEach(a=>{const h=a.getAttribute('href');if(h===p||(p===''&&h==='index.html'))a.classList.add('active')});
  
  // Cookies
  if(!localStorage.getItem('ah_ck')){const b=document.querySelector('.ck-banner');if(b){setTimeout(()=>b.classList.add('visible'),1200);b.querySelector('.cka')?.addEventListener('click',()=>{localStorage.setItem('ah_ck','1');b.classList.remove('visible')});b.querySelector('.ckr')?.addEventListener('click',()=>{localStorage.setItem('ah_ck','0');b.classList.remove('visible')})}}
  
  // Animations
  const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.1});
  document.querySelectorAll('.anim').forEach(el=>obs.observe(el));
  
  // Contact form
  const f=document.getElementById('cForm');
  if(f)f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('button[type=submit]'),o=btn.textContent;btn.disabled=true;btn.textContent='...';try{const r=await fetch('https://formsubmit.co/ajax/hibanezborreguero@gmail.com',{method:'POST',body:new FormData(f)});if(r.ok){btn.textContent='✓';f.reset();setTimeout(()=>{btn.textContent=o;btn.disabled=false},3000)}else throw 0}catch{btn.textContent=o;btn.disabled=false;alert('Error')}};
  
  setLang(LANG);
});
